### ISSUE TITLE
In certain conditions CmisRequest is invoked with undefined res

### ISSUE THREAD

**Issue by e-voci** [agea/CmisJS#40]
I am using cmis 0.3.0.
It happened that a request has been interrupted by an error, and the system crashed with the following trace:
node_modules/cmis/lib/cmis.js:1161
          if (res.ok) {
                 ^
TypeError: Cannot read property 'ok' of undefined
    at /node_modules/cmis/lib/cmis.js:1161:18
    at Request.callback (/node_modules/cmis/node_modules/superagent/lib/node/index.js:815:12)
    at /node_modules/cmis/node_modules/superagent/lib/node/index.js:1011:43
    at IncomingMessage.<anonymous> (/node_modules/cmis/node_modules/superagent/lib/node/parsers/json.js:14:7)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickCallback (node.js:351:17)

**Comment by agea** [comment]
It should be related to issue #39, when making a request with a special character not encoded in the path Alfresco returns an invalid response, can you try to reproduce it with the master version (6afc9a2) of the library?

**Comment by fernandojunior** [comment]
Just an idea. Why do not you use the `$http` from AngularJS instead of `_http`? $http returns a promise (then, finally, catch), so you can eliminate `CmisRequest`. `$.ajax` from jQuery also returns a promise.
